# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/JWT" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" 
    directory: "/UserAuth" 
    schedule:
      interval: "daily"
